src/django_2_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# https://youtu.be/04L0BbAcCpQ?t=5604
# part 11

src/reports/urls.py
from django.urls import path
from .views import (
    create_reports_view,
    ReportListView,
    ReportDetailView,
    render_pdf_view,
    UploadTemplateView,
    csv_upload_view
)

app_name = 'reports'

urlpatterns = [
    path('', ReportListView.as_view(), name='main'),
    path('save/', create_reports_view, name='create-report'),
    path('upload/', csv_upload_view, name='upload'),
    path('from_file', UploadTemplateView.as_view(), name='from-file'),
    path('<pk>/', ReportDetailView.as_view(), name='detail'),
    path('<pk>/pdf/', render_pdf_view, name='pdf')
]

src/sales/urls.py
from django.urls import URLPattern, path
from .views import (
    home_view,
    SalesListView,
    SaleDetailView,
)

app_name = 'sales'

urlpatterns = [
    path('', home_view, name='home'),
    path('sales/', SalesListView.as_view(), name='list'),
    path('sales/<pk>', SaleDetailView.as_view(), name='detail'),
]

src/reports/models.py
from operator import mod
from pyexpat import model
from django.db import models
from profiles.models import Profile
from django.urls import reverse

# Create your models here.

class Report(models.Model):
    name = models.CharField(max_length=120)
    image = models.ImageField(upload_to='reports', blank=True)
    remarks = models.TextField()
    #author = models.ForeignKey(Profile, on_delete=models.CASCADE) removig author for the time being as this errors, not pulling profile through to report
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('reports:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ('created', )

src/reports/forms.py
from django import forms
from .models import Report

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name', 'remarks')

src/reports/views.py
from django.shortcuts import render, get_object_or_404
from profiles.models import Profile
from django.http import JsonResponse, HttpResponse
from .utils import get_report_image
from .models import Report
from django.views.generic import ListView, DetailView, TemplateView
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.conf import settings

from sales.models import Sale, Position, CSV
import csv
# Create your views here.

class ReportListView(ListView):
    model = Report
    template_name = 'reports/main.html'

class ReportDetailView(DetailView):
    model = Report
    template_name = 'reports/detail.html'

class UploadTemplateView(TemplateView):
    template_name = 'reports/from_file.html'

def csv_upload_view(request):
    if request.method == 'POST':
        csv_file = request.FILES.get('file')
        obj = CSV.objects.create(file_name=csv_file)

        with open(obj.file_name.path, 'r') as f:
            reader = csv.reader(f)
            for row in reader:
                print(row, type(row))

    return HttpResponse()

def create_reports_view(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        name = request.POST.get('name')
        remarks = request.POST.get('remarks')
        image = request.POST.get('image')

        img = get_report_image(image)

        #author = Profile.objects.get(user=request.user) this is causing the error
        Report.objects.create(name=name, remarks=remarks, image=img)
        return JsonResponse({'msg': 'send'})
    return JsonResponse({})

    #create a PDF
def render_pdf_view(request, pk):
    template_path = 'reports/pdf.html'
    obj = get_object_or_404(Report, pk=pk)
    context = {'obj': obj}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # if download the pdf, the below
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # if display the pdf, the below
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funny view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

src/reports/templates/reports/detail.html
{% extends 'base.html' %}

{% block title %}
    {{object.name}}
{% endblock title %}

{% block content %}
    {% if object.image %}
        <img src=" {{object.image.url}} " class="img-fluid" alt=" {{object.name}}">

    {% endif %}
    <br>
    <h3> Remarks </h3>
    <p> {{ object.remarks }} </p>
    <hr>
    <p> author: <br> {{ object.author.user.username}} <br> </p>
    <p> created: <br> {{ object.created }} <br> </p>

{% endblock content %}

src/reports/templates/reports/from_file.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
<script src="{% static 'reports/upload.js' %}" defer></script>
{% endblock scripts %}


{% block title %}
Upload sales files
{% endblock title %}



{% block content %}
    <h5> Upload your sales documents here</h5>
    <br>
    <form id="my-dropzone" class="dropzone dz">
        {% csrf_token %}
        <div class="fallback">
            <input name="file" type="file" multiple />
        </div>
    </form>
{% endblock content %}

src/reports/templates/reports/main.html
{% extends "base.html" %}
reports
{% block title %}
    reports
{% endblock title %}

{% block content %}
    Report list
    <br>
    <br>

{% for obj in object_list %}
        <div class="card mb-3" style="width: 18rem;">
            {% if obj.image %}
                <img src="{{ obj.image.url }}" class="card-img-top" alt="{{ obj.image }}">
            {% endif %}

            <div class="card-body">
            <h5 class="card-title"> <a href={{ obj.get_absolute_url}}> {{obj.name}} </a> </h5>
            
            <p class="card-text"> {{obj.remarks|truncatewords:2}}</p>
            <a href="{{obj.get_absolute_url}}" class="btn btn-primary"> Details </a>
            <a href="{% url 'reports:pdf' obj.pk %}" class="btn btn-danger"> PDF </a>
            </div>
        </div>

{% endfor %}
{% endblock content %}

src/reports/templates/reports/pdf.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title> PDF {{obj.name}} </title>
  <style>
      .image {
          width: 100%;
          height: auto;
      }
  </style>
</head>
<body>
    <h1> {{obj.name}} </h1>
    <hr>
    <img src='{{obj.image.path}}' class="image">
    <br>
    <h3> Remarks</h3>
    <p> {{obj.remarks}}</p>
    <hr>
    <p> author: <br> {{obj.author.user.username}} </p>
    <p> created: <br> {{obj.created}} </p>
</body>
</html>

src/reports/templates/reports/upload.html
{% extends 'base.html' %}

{% block title %}
    {{object.name}}
{% endblock title %}

{% block content %}
    {% if object.image %}
        <img src=" {{object.image.url}} " class="img-fluid" alt=" {{object.name}}">

    {% endif %}
    <br>
    <h3> Remarks </h3>
    <p> {{ object.remarks }} </p>
    <hr>
    <p> author: <br> {{ object.author.user.username}} <br> </p>
    <p> created: <br> {{ object.created }} <br> </p>

{% endblock content %}